// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAGmS-oGTj-1SaU7PzHObxy9rfBJ-GFY4',
    appId: '1:947646602761:web:82ad2a63a10d67f7b8e2d8',
    messagingSenderId: '947646602761',
    projectId: 'techtide-f60e0',
    authDomain: 'techtide-f60e0.firebaseapp.com',
    storageBucket: 'techtide-f60e0.appspot.com',
    measurementId: 'G-M13NR3R4M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKOCGNcjUCsZKh0BHi4tENyVwTicxdJzI',
    appId: '1:947646602761:android:f999f725888c695cb8e2d8',
    messagingSenderId: '947646602761',
    projectId: 'techtide-f60e0',
    storageBucket: 'techtide-f60e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUrjm0jZ2UYx7Vl5Y0S6bTFO2G75IazgQ',
    appId: '1:947646602761:ios:950db51a05efaccbb8e2d8',
    messagingSenderId: '947646602761',
    projectId: 'techtide-f60e0',
    storageBucket: 'techtide-f60e0.appspot.com',
    iosBundleId: 'com.example.techTide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUrjm0jZ2UYx7Vl5Y0S6bTFO2G75IazgQ',
    appId: '1:947646602761:ios:950db51a05efaccbb8e2d8',
    messagingSenderId: '947646602761',
    projectId: 'techtide-f60e0',
    storageBucket: 'techtide-f60e0.appspot.com',
    iosBundleId: 'com.example.techTide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAGmS-oGTj-1SaU7PzHObxy9rfBJ-GFY4',
    appId: '1:947646602761:web:389f73c13f23cc9eb8e2d8',
    messagingSenderId: '947646602761',
    projectId: 'techtide-f60e0',
    authDomain: 'techtide-f60e0.firebaseapp.com',
    storageBucket: 'techtide-f60e0.appspot.com',
    measurementId: 'G-1KM1RT81HV',
  );
}
